-- APN Hungary Platform — APN Disease Library (Betegségtár)

create table public.diseases (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  aliases text[] not null default '{}',
  abbrev text,
  specialty text,
  context_id text,
  score_ids text[] not null default '{}',
  lab_ids text[] not null default '{}',
  ekg_ids text[] not null default '{}',
  guideline_kw text[] not null default '{}',
  body jsonb not null default '{}'::jsonb,
  status text not null default 'published' check (status in ('draft','review','published','expired')),
  version text,
  review_on date,
  expires_on date,
  ai_generated boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  reviewed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_disease_spec on public.diseases(specialty);
create index idx_disease_ctx on public.diseases(context_id);

alter table public.diseases enable row level security;
create policy "disease: olvasás" on public.diseases for select
  using (status = 'published' or has_role(array['szerkeszto','lektor','admin']) or created_by = auth.uid());
create policy "disease: staff felvitel" on public.diseases for insert
  with check (has_role(array['szerkeszto','lektor','admin']));
create policy "disease: staff módosítás" on public.diseases for update
  using (has_role(array['szerkeszto','lektor','admin']));
create policy "disease: staff törlés" on public.diseases for delete
  using (has_role(array['szerkeszto','lektor','admin']));

insert into public.diseases (slug, name, aliases, abbrev, specialty, context_id, score_ids, lab_ids, ekg_ids, guideline_kw, body, status, version) values
  ('copd', 'COPD (krónikus obstruktív tüdőbetegség)', '{"krónikus obstruktív tüdőbetegség","idült hörghurut","emfizéma"}', 'COPD', 'Pulmonológia', 'copd', '{"cat","mmrc","curb65","news2"}', '{"crp","wbc","ph","lact"}', '{}', '{"copd","obstruktiv"}', '{"brief_what": "Krónikus, jórészt visszafordíthatatlan légúti obstrukció, tartós tünetekkel.", "brief_why": "Gyakori, jól gondozható; az exacerbáció felismerése és a helyes inhalációs technika APN-kulcsfeladat.", "when": ["Krónikus köhögés, köpetürítés, terhelési nehézlégzés", "Dohányzás/expozíció az anamnézisben", "Fokozódó dyspnoe, köpet-purulencia = exacerbáció"], "examine": ["Légzésszám, SpO₂, munkalégzés", "Hallgatózás (sípolás, meghosszabbodott kilégzés)", "Cyanosis, perifériás ödéma"], "labs": "Exacerbáció/infekció gyanújánál CRP, fehérvérsejt; súlyos esetben vérgáz (pH, pCO₂).", "ekg": "Rutinszerűen nem szükséges; társ-szívbetegség vagy ritmuszavar gyanújánál igen.", "imaging": "Mellkasröntgen az exacerbáció/pneumónia elkülönítésére; spirometria a diagnózishoz.", "scores": "CAT és mMRC a tünetterhelés méréséhez; NEWS2 az akut súlyosság megítéléséhez.", "red_flags": ["SpO₂ tartós csökkenés, cyanosis, zavartság (CO₂-narkózis jele)", "Kimerülés, beszédképtelenség, paradox légzés", "NEWS2 magas / gyors romlás"], "apn_focus": ["Inhalációs technika és adherencia ellenőrzése", "Oxigén ÓVATOSAN, célszaturáció jellemzően 88–92%", "Exacerbáció korai jeleinek betegoktatása", "Dohányzásleszokás támogatása, védőoltások"], "treatment": ["Hörgtágítók (LABA/LAMA), tünet szerint SABA", "Súlyos/gyakori exacerbációnál inhalációs szteroid mérlegelése (orvosi döntés)", "Pulmonális rehabilitáció, oltások"], "followup": ["Rendszeres tünet- és inhalációs kontroll", "Exacerbáció-terv, önmonitorozás", "Komorbiditások (szív, szorongás) követése"], "source_name": "Nemzetközi ajánlás (GOLD) és hazai tüdőgyógyászati irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('asthma', 'Asthma bronchiale', '{"asztma","hörgőasztma"}', null, 'Pulmonológia', null, '{"cat","mmrc"}', '{}', '{}', '{"asztma"}', '{"brief_what": "Krónikus légúti gyulladás, változó, reverzibilis obstrukcióval.", "brief_why": "Jó kontroll mellett tünetmentesség érhető el; a roham felismerése és a technika APN-feladat.", "when": ["Rohamszerű nehézlégzés, sípolás, éjszakai köhögés", "Allergiás anamnézis, trigger-expozíció", "Terhelésre/allergénre romló tünetek"], "examine": ["Légzésszám, SpO₂, sípolás", "Beszédképesség, munkalégzés", "PEF, ha elérhető"], "labs": "Rutinlabor nem specifikus; eozinofília, allergiavizsgálat a kivizsgálásban.", "ekg": "Nem jellemző; differenciáldiagnózisban lehet szükséges.", "imaging": "Spirometria/PEF a diagnózishoz; mellkasröntgen szövődmény gyanújánál.", "scores": "CAT/mMRC tájékozódó jelleggel; a kontroll megítélése tünet-alapú.", "red_flags": ["Néma tüdő, cyanosis, kimerülés", "Beszédképtelenség, SpO₂ csökkenés", "PEF erős csökkenése, rohamoldó hatástalansága"], "apn_focus": ["Inhalációs technika, adherencia, akcióterv", "Trigger-kerülés oktatása", "Roham korai kezelésének betegoktatása"], "treatment": ["Fenntartó inhalációs szteroid ± LABA", "Rohamoldó szükség szerint", "Súlyos asztma: szakorvosi gondozás"], "followup": ["Kontrollszint rendszeres értékelése", "Akcióterv frissítése", "Komorbiditások (rhinitis) kezelése"], "source_name": "Nemzetközi ajánlás (GINA) és hazai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('hypertonia', 'Hypertonia (magasvérnyomás-betegség)', '{"magasvérnyomás","magas vérnyomás","HTN"}', 'HT', 'Kardiológia', null, '{}', '{"krea","egfr","na","k","gluk","chol","ldl"}', '{"lbbb"}', '{"hypertonia","vérnyomás"}', '{"brief_what": "Tartósan emelkedett artériás vérnyomás, jelentős kardiovaszkuláris kockázattal.", "brief_why": "Népbetegség; a szűrés, adherencia és rizikócsökkentés APN-központú feladat.", "when": ["Gyakran tünetmentes; fejfájás, szédülés nem specifikus", "Rizikófaktorok: elhízás, só, dohányzás, család", "Célszervkárosodás jelei előrehaladott esetben"], "examine": ["Standardizált vérnyomásmérés (mindkét kar)", "BMI, haskörfogat", "Célszerv-eltérések keresése"], "labs": "Vesefunkció (krea/eGFR), ionok, vércukor, lipidek; vizelet fehérje.", "ekg": "Bal kamra hypertrophia jelei; ritmuszavar szűrése.", "imaging": "Célszervkárosodás gyanújánál (szív-UH, szemfenék) — szakorvosi.", "scores": "SCORE2-típusú kockázatbecslés a kivizsgálásban; BMI.", "red_flags": ["Hypertóniás sürgősség: nagyon magas RR + célszervi tünet (mellkasi fájdalom, neurológiai jel, tüdőödéma)", "Terhességi hypertonia jelei"], "apn_focus": ["Pontos, standardizált mérés és otthoni monitorozás oktatása", "Só-/életmód-tanácsadás, adherencia", "Rizikófaktorok együttes kezelése"], "treatment": ["Életmód + gyógyszercsoportok (ACEi/ARB, Ca-antagonista, diuretikum)", "Egyénre szabott célérték (orvosi döntés)", "Kombináció gyakran szükséges"], "followup": ["Rendszeres RR-kontroll, otthoni napló", "Célszervek és vesefunkció követése", "Adherencia és mellékhatás monitorozás"], "source_name": "Nemzetközi ajánlás (ESC/ESH) és hazai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('dm2', 'Diabetes mellitus 2-es típus', '{"cukorbetegség","2-es típusú diabétesz","T2DM"}', 'DM2', 'Anyagcsere / endokrinológia', 'diabetesz', '{"findrisc","bmi"}', '{"gluk","hba1c","ldl","egfr","krea"}', '{}', '{"diabet","cukor","retinopath"}', '{"brief_what": "Inzulinrezisztencián alapuló krónikus hyperglykaemia.", "brief_why": "Szövődményei megelőzhetők; a szűrés, oktatás és monitorozás APN-feladat.", "when": ["Gyakran tünetszegény; polyuria, polydipsia, fáradtság", "Rizikó: elhízás, család, mozgásszegény életmód", "Szövődmények: szem, vese, ideg, érrendszer"], "examine": ["BMI, haskörfogat, vérnyomás", "Láb-status (neuropathia, keringés)", "Célszervek szűrése"], "labs": "Éhomi vércukor, HbA1c; lipidek, vesefunkció, vizelet albumin.", "ekg": "Társ-szívbetegség gyanújánál; néma ischaemia lehetősége.", "imaging": "Szemfenék (retinopathia) szűrés; szövődmény-specifikus vizsgálatok.", "scores": "FINDRISC a kockázatbecsléshez; BMI.", "red_flags": ["Nagyon magas vércukor + keton/aceton = DKA/HHS gyanú, sürgős", "Hypoglykaemia tünetei", "Diabéteszes láb fertőzésének jelei"], "apn_focus": ["Önmonitorozás, hypo-felismerés oktatása", "Láb- és szemszűrés szervezése", "Életmód, adherencia, rizikócsökkentés"], "treatment": ["Életmód + metformin alap; egyénre szabott továbblépés (orvosi döntés)", "Kardiovaszkuláris/vese-védő szerek mérlegelése", "Társbetegségek együtt-kezelése"], "followup": ["HbA1c 3–6 havonta", "Szövődmény-szűrések éves rendje", "Vérnyomás/lipid célok követése"], "source_name": "Nemzetközi ajánlás (ADA/EASD) és hazai diabetológiai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('szivelegtelenseg', 'Szívelégtelenség', '{"keringési elégtelenség","HF","dekompenzáció"}', 'HF', 'Kardiológia', 'szivelegtelenseg', '{"news2"}', '{"bnp","krea","na","k"}', '{"afib","lbbb"}', '{"szivelegtelen","szív"}', '{"brief_what": "A szív elégtelen pumpafunkciója, pangásos/kisperctérfogatú tünetekkel.", "brief_why": "Gyakori kórházi visszavétel; a testsúly/folyadék monitorozása APN-kulcs.", "when": ["Terhelési/nyugalmi dyspnoe, ortopnoe, ödéma", "Fáradtság, éjszakai köhögés", "Hirtelen testsúlynövekedés"], "examine": ["Vitálisok, SpO₂, pangásjelek (tüdő, jugularis, ödéma)", "Testsúly", "Perifériás keringés"], "labs": "NT-proBNP; vesefunkció, ionok (Na, K) a terápia miatt.", "ekg": "Alapritmus, pitvarfibrilláció, szárblokk, ischaemia.", "imaging": "Szív-UH a diagnózishoz/EF-hez; mellkasröntgen pangáshoz.", "scores": "NEWS2 az akut súlyossághoz.", "red_flags": ["Súlyos nyugalmi dyspnoe, tüdőödéma, hypotensio/shock", "Gyors testsúlynövekedés, anuria", "Új ritmuszavar instabilitással"], "apn_focus": ["Napi testsúly és folyadékkorlát oktatása", "Terápiahűség, só-korlát", "Korai dekompenzáció jeleinek felismerése"], "treatment": ["Alapterápia: ACEi/ARNI, béta-blokkoló, MRA, SGLT2i (orvosi beállítás)", "Diuretikum a pangásra", "Ok-specifikus kezelés"], "followup": ["Rendszeres testsúly/tünet-napló", "Vesefunkció/ion kontroll", "Oltások, komorbiditások"], "source_name": "Nemzetközi ajánlás (ESC) és hazai kardiológiai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('pitvarfibrillacio', 'Pitvarfibrilláció', '{"AF","AFib","pitvari fibrilláció"}', 'AF', 'Kardiológia', 'pitvarfibrillacio', '{"cha2ds2","hasbled"}', '{"tsh","k","ft4"}', '{"afib","aflutter"}', '{"pitvarfibrill","antikoagul","ritmus"}', '{"brief_what": "Szabálytalan pitvari ritmus, fokozott stroke-kockázattal.", "brief_why": "A stroke-megelőzés (antikoagulálás mérlegelése) és a frekvencia-kontroll kulcs.", "when": ["Palpitáció, fáradtság, dyspnoe; gyakran tünetszegény", "Szabálytalan pulzus", "Thromboemboliás rizikó"], "examine": ["Pulzus (szabálytalan), vérnyomás", "Szívelégtelenség jelei", "Stroke-rizikó felmérése"], "labs": "TSH/fT4 (pajzsmirigy), ionok (K); vesefunkció az antikoagulálás miatt.", "ekg": "12 elvezetéses EKG a diagnózishoz (szabálytalan RR, hiányzó P).", "imaging": "Szív-UH strukturális ok/thrombus megítéléséhez.", "scores": "CHA₂DS₂-VASc a stroke-, HAS-BLED a vérzési kockázathoz.", "red_flags": ["Hemodinamikai instabilitás gyors kamrai válasznál, sürgős", "Új neurológiai gócjel (stroke)", "Nagyon gyors/lassú kamrafrekvencia tünettel"], "apn_focus": ["Pulzus-önellenőrzés oktatása", "Antikoaguláns-adherencia és vérzésjelek figyelése", "Rizikófaktor-kezelés"], "treatment": ["Frekvencia- vagy ritmuskontroll (orvosi döntés)", "Antikoagulálás a rizikó szerint", "Kiváltó ok kezelése"], "followup": ["INR/vesefunkció szükség szerint", "Ritmus/frekvencia követése", "Stroke-jelek betegoktatása"], "source_name": "Nemzetközi ajánlás (ESC) és hazai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('stroke', 'Stroke / TIA', '{"agyi érkatasztrófa","szélütés","TIA","tranziens ischaemiás attak"}', null, 'Neurológia', 'stroke', '{"fast","cincinnati","abcd2","gcs","nihss"}', '{"gluk"}', '{"afib"}', '{"stroke","tia","neurolog","agyi"}', '{"brief_what": "Az agyi keringés akut zavara; TIA esetén átmeneti, maradványtünet nélkül.", "brief_why": "Időfüggő ellátás (time is brain); a gyors felismerés életmentő.", "when": ["Hirtelen féloldali gyengeség, beszédzavar, arcaszimmetria", "Látászavar, szédülés, tudatzavar", "Kezdet pontos időpontja kulcs"], "examine": ["FAST-vizsgálat, GCS", "Vitálisok, vércukor (hypoglykaemia kizárása!)", "Fokális neurológiai jelek"], "labs": "Vércukor azonnal (hypoglykaemia utánozhatja); alvadás, ionok a kivizsgálásban.", "ekg": "Pitvarfibrilláció keresése (embóliaforrás).", "imaging": "Sürgős koponya-CT/MR (vérzés/ischaemia elkülönítés) — kórházi.", "scores": "FAST/Cincinnati a felismeréshez, NIHSS a súlyossághoz, ABCD² a TIA-rizikóhoz.", "red_flags": ["Akut fokális neurológiai tünet, AZONNALI mentő, időablak!", "Tudatzavar, légúti veszély", "Nagyon magas vérnyomás + neurológiai jel"], "apn_focus": ["FAST gyors alkalmazása, kezdet idejének rögzítése", "Vércukor ellenőrzése", "Sürgős transzport szervezése, betegoktatás"], "treatment": ["Akut reperfúzió időablakban (kórházi, orvosi döntés)", "Másodlagos prevenció (vérnyomás, antithrombotikum, lipid)", "Rehabilitáció"], "followup": ["Rizikófaktor-gondozás (RR, AF, DM, lipid)", "Adherencia, ismételt esemény jeleinek oktatása", "Funkcionális utánkövetés"], "source_name": "Nemzetközi ajánlás (ESO/AHA) és hazai neurológiai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('pneumonia', 'Pneumonia (tüdőgyulladás)', '{"tüdőgyulladás","alsó légúti infekció","CAP"}', null, 'Infektológia', 'pneumonia', '{"curb65","news2","qsofa"}', '{"crp","wbc","pct"}', '{}', '{"pneumonia","fertoz","tudogyullad"}', '{"brief_what": "A tüdő fertőzéses gyulladása, jellemzően bakteriális eredettel.", "brief_why": "A súlyosság (CURB-65) és a szepszis-jelek felismerése dönti el az ellátás szintjét.", "when": ["Láz, produktív köhögés, mellkasi fájdalom, dyspnoe", "Idős/komorbid betegnél atípusos kép", "Zavartság időseknél"], "examine": ["Légzésszám, SpO₂, láz, vérnyomás", "Hallgatózás (crepitatio)", "Tudatállapot"], "labs": "CRP, fehérvérsejt; súlyosnál PCT, laktát, vérgáz.", "ekg": "Rutinszerűen nem; társbetegség szerint.", "imaging": "Mellkasröntgen a diagnózishoz.", "scores": "CURB-65 a súlyossághoz, NEWS2/qSOFA a romlás/szepszis megítéléséhez.", "red_flags": ["qSOFA ≥2, hypotensio, magas légzésszám, szepszis gyanú", "Súlyos hypoxia, zavartság", "Gyors klinikai romlás"], "apn_focus": ["Vitálisok és SpO₂ követése", "Súlyossági score alkalmazása", "Folyadék/oxigén és betegoktatás"], "treatment": ["Empirikus antibiotikum a súlyosság/helyi protokoll szerint (orvosi döntés)", "Oxigén, folyadék", "Oltások prevencióban"], "followup": ["Klinikai válasz követése", "Kontroll szükség szerint", "Oltási státusz rendezése"], "source_name": "Nemzetközi/hazai pneumónia-irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('sepsis', 'Sepsis', '{"szepszis","vérmérgezés","szeptikus állapot"}', null, 'Akut állapotok', 'szepszis', '{"qsofa","news2","sofa"}', '{"crp","wbc","pct","lact"}', '{}', '{"fertoz","szepszis"}', '{"brief_what": "Fertőzésre adott szabályozatlan válasz életveszélyes szervi diszfunkcióval.", "brief_why": "Időkritikus: a korai felismerés és ellátás jelentősen javítja a kimenetelt.", "when": ["Fertőzés + akut állapotromlás", "Láz vagy hypothermia, tachycardia, tachypnoe", "Zavartság, csökkent diurézis"], "examine": ["Teljes vitális felmérés, SpO₂, tudat", "Perfúzió (bőr, kapilláris újratelődés)", "Fertőzési góc keresése"], "labs": "Laktát, CRP/PCT, fehérvérsejt, vesefunkció; hemokultúra láznál.", "ekg": "Ritmuszavar/ischaemia kísérőként.", "imaging": "Góc-keresés a klinikai kép szerint (rtg, UH).", "scores": "qSOFA/SOFA a szervi diszfunkcióhoz, NEWS2 a romláshoz.", "red_flags": ["qSOFA ≥2 vagy emelkedett laktát, AZONNALI ellátás", "Hypotensio, oliguria, tudatzavar", "Gyors romlás"], "apn_focus": ["Korai felismerés, szepszis-protokoll indítása", "Vitálisok szoros követése, laktát-kontroll", "Sürgős orvosi értesítés"], "treatment": ["Időben adott antibiotikum, folyadékreszuszcitáció, góckontroll (kórházi, orvosi)", "Szervtámogatás szükség szerint"], "followup": ["Lábadozás, ok-kezelés", "Rizikó/prevenció oktatása", "Utánkövetés"], "source_name": "Sepsis-3 definíció és nemzetközi/hazai szepszis-ajánlás", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('ckd', 'Krónikus vesebetegség (CKD)', '{"krónikus vesebetegség","veseelégtelenség","CKD"}', 'CKD', 'Nefrológia', 'vesekarosodas', '{}', '{"krea","urea","egfr","k","na","ca","phos"}', '{"hyperk"}', '{"vese"}', '{"brief_what": "Tartósan csökkent vesefunkció (eGFR) és/vagy vesekárosodás jelei.", "brief_why": "A progresszió lassítható; a gyógyszerdózisok és a kálium követése kritikus.", "when": ["Gyakran tünetszegény; fáradtság, ödéma előrehaladottan", "Rizikó: DM, hypertonia", "Anaemia, csontanyagcsere-zavar"], "examine": ["Vérnyomás, folyadékstátusz", "Ödéma, volumen", "Gyógyszer-áttekintés"], "labs": "Kreatinin/eGFR, ionok (K!), Ca/Foszfát, vizelet albumin; anaemia.", "ekg": "Hyperkalaemia EKG-jelei (csúcsos T).", "imaging": "Vese-UH a strukturális okhoz.", "scores": "eGFR-alapú stádiumbeosztás; kardiovaszkuláris kockázat.", "red_flags": ["Hyperkalaemia (EKG-eltérés), sürgős", "Gyors eGFR-romlás, oliguria", "Túltöltés/tüdőödéma"], "apn_focus": ["Nefrotoxikus szerek kerülése, dózis eGFR-hez", "Kálium/folyadék figyelése", "Vérnyomás- és rizikókezelés oktatása"], "treatment": ["Alapbetegség (DM, HT) kezelése, vese-védő szerek (orvosi)", "Szövődmények (anaemia, csont) kezelése", "Diéta szükség szerint"], "followup": ["eGFR/ion rendszeres kontroll", "Progresszió és szövődmények követése", "Gyógyszerbiztonság"], "source_name": "Nemzetközi ajánlás (KDIGO) és hazai nefrológiai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('diabeteses_lab', 'Diabéteszes láb', '{"diabéteszes lábszindróma","cukorbeteg láb"}', null, 'Sebészet / sebkezelés', null, '{"braden","norton"}', '{"crp","wbc","gluk","hba1c"}', '{}', '{"seb","diabet"}', '{"brief_what": "Diabéteszhez társuló láb-szövődmény: neuropathia, ischaemia, fekély, fertőzés.", "brief_why": "Megelőzhető és korán kezelhető; a rendszeres lábszűrés APN-feladat.", "when": ["Érzészavar, deformitás, callus, fekély", "Rossz sebgyógyulás, láb-fájdalom vagy annak hiánya", "Fertőzés jelei"], "examine": ["Láb-inspekció, érzés- és keringésvizsgálat", "Sebállapot dokumentálása", "Lábbeli, nyomáspontok"], "labs": "Fertőzés gyanújánál CRP/fehérvérsejt; anyagcsere-kontroll (gluk, HbA1c).", "ekg": "Nem jellemző.", "imaging": "Csontérintettség/keringés gyanújánál képalkotás — szakorvosi.", "scores": "Decubitus-rizikó eszközök (Braden/Norton) analóg alkalmazása a bőrveszélyhez.", "red_flags": ["Terjedő fertőzés, láz, gennyes/necroticus seb, sürgős", "Kritikus végtag-ischaemia jelei", "Rossz szagú, gyorsan romló seb"], "apn_focus": ["Napi lábellenőrzés és megfelelő lábbelinek oktatása", "Sebkezelés, nyomásmentesítés", "Anyagcsere-optimalizálás, keringés értékelése"], "treatment": ["Sebellátás, tehermentesítés, fertőzés kezelése (orvosi/multidiszciplináris)", "Keringés helyreállítása szükség szerint", "Glykaemiás kontroll"], "followup": ["Rendszeres lábszűrés, önvizsgálat", "Recidíva-megelőzés", "Multidiszciplináris gondozás"], "source_name": "Nemzetközi ajánlás (IWGDF) és hazai irányelv", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026'),
  ('dementia_delirium', 'Dementia / delirium', '{"demencia","zavartság","delírium","kognitív hanyatlás"}', null, 'Geriátria', 'eses_geriatria', '{"minicog","mmse","moca","camicu","cfs"}', '{"na","ca","tsh","b12"}', '{}', '{"geriatr","delirium","dementia"}', '{"brief_what": "Dementia: krónikus, progresszív kognitív hanyatlás. Delirium: akut, fluktuáló tudat-/figyelemzavar.", "brief_why": "A delirium akut, gyakran visszafordítható és sürgős, mindig el kell különíteni a dementiától.", "when": ["Dementia: fokozatos memória-/funkcióromlás", "Delirium: hirtelen zavartság, figyelemingadozás", "Kiváltó ok (infekció, gyógyszer, ion) delíriumban"], "examine": ["Kogníció (MMSE/MoCA/Mini-Cog), figyelem (CAM-ICU)", "Vitálisok, hidráltság, fájdalom", "Gyógyszer-áttekintés (polypharmacia)"], "labs": "Delíriumban ok-keresés: ionok (Na, Ca), vércukor, TSH, B12, gyulladás, vizelet.", "ekg": "Nem jellemző; kiváltó ok szerint.", "imaging": "Új fokális tünet vagy trauma gyanújánál koponya-képalkotás.", "scores": "Mini-Cog/MMSE/MoCA a kognícióhoz, CAM-ICU a delíriumhoz, CFS a frailtyhez.", "red_flags": ["Akut zavartság (delirium), kiváltó ok keresése, sürgős értékelés", "Új fokális neurológiai jel", "Agitáció önveszéllyel, dehidráció, szepszis"], "apn_focus": ["Delirium és dementia elkülönítése", "Kiváltó okok (infekció, gyógyszer, fájdalom, ion) keresése", "Orientáció, biztonság, hozzátartozó bevonása"], "treatment": ["Delirium: kiváltó ok kezelése, nem-gyógyszeres teendők előny", "Dementia: gondozás, tüneti kezelés (orvosi)", "Polypharmacia felülvizsgálata"], "followup": ["Kognitív és funkcionális követés", "Esés-/biztonsági terv", "Gondozói támogatás"], "source_name": "Hazai geriátriai és nemzetközi delirium/dementia ajánlás", "source_url": "", "version": "MVP 2026", "updated": "2026-08-14", "evidence": "szakmai irányelv / konszenzus"}'::jsonb, 'published', 'MVP 2026')
on conflict (slug) do nothing;
