-- APN Hungary Platform — D fázis: 10 demó kórkép bővített, evidence-jelölt tartalma
-- Minden tétel 'review_pending' (lektorálásra vár); a reviewer-lista üres (valódi lektor rendeli hozzá).
-- Klinikai tartalom szakmai tájékoztató szinten; a hivatkozott irányelvek a tartalom alapját jelölik.

update public.diseases set
  epidemiology='A felnőtt lakosság kb. 30–45%-át érinti, prevalenciája az életkorral nő. Vezető módosítható rizikófaktor a cardiovascularis és renalis megbetegedésekben.', pathophysiology='Perzisztensen emelkedett artériás nyomás a perctérfogat és/vagy a perifériás ellenállás növekedése révén; hosszú távon érfali remodelling, endothel-diszfunkció, cél-szervi károsodás (szív, vese, agy, retina).',
  ddx='[{"name": "Fehérköpeny-hypertonia", "slug": "feherkopeny_hypertonia"}, {"name": "Álhypertonia", "slug": "alhypertonia"}, {"name": "Szekunder hypertonia", "slug": "szekunder_hypertonia"}, {"name": "Feochromocytoma", "slug": "feochromocytoma"}, {"name": "Primer hyperaldosteronismus", "slug": "primer_hyperaldosteronismus"}, {"name": "Veseeredetű hypertonia", "slug": "veseeredetu_hypertonia"}, {"name": "Obstructiv alvási apnoe", "slug": "obstructiv_alvasi_apnoe"}]'::jsonb,
  apn_approach='{"anamnesis": "Rizikófaktorok, családi anamnézis, só- és alkoholbevitel, gyógyszerek (NSAID, dekongesztáns, fogamzásgátló), OSA-tünetek, korábbi értékek.", "physical": "Ismételt, standardizált vérnyomásmérés mindkét karon, testtömeg/haskörfogat, célszervi jelek (szívzörej, carotis-zörej, perifériás pulzusok, oedema).", "data": "Otthoni/ABPM mérések, vizelet, ionok, kreatinin/eGFR, vércukor, lipidek, EKG; célszervi károsodás felmérése.", "thinking": "Valódi tartós emelkedés vs. fehérköpeny; primer vs. szekunder ok mérlegelése fiatal korban, terápia-rezisztenciánál vagy hirtelen romlásnál.", "consultation": "Szekunder ok gyanúja, terápia-rezisztencia, terhesség, célszervi károsodás esetén orvosi konzultáció.", "escalation": "Hypertoniás sürgősségi állapot (célszervi károsodással) azonnali ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "ESC/ESH 2023 hypertonia irányelv", "kezeles": "ESC/ESH 2023"}'::jsonb, review_on='2027-08-01'
where slug='hypertonia';
update public.diseases set
  epidemiology='A felnőttek kb. 1–2%-át érinti, 70 év felett >10%. Gyakori kórházi felvételi ok, magas rehospitalizációs és mortalitási aránnyal.', pathophysiology='A szív elégtelen perctérfogata és/vagy emelkedett töltőnyomása; neurohormonális aktiváció (RAAS, szimpatikus), folyadékretenció, remodelling. Fenotípusok: csökkent (HFrEF), enyhén csökkent (HFmrEF), megtartott (HFpEF) ejekciós frakció.',
  ddx='[{"name": "COPD", "slug": "copd"}, {"name": "Pneumonia", "slug": "pneumonia"}, {"name": "Pulmonalis embolia", "slug": "pulmonalis_embolia"}, {"name": "Vesebetegség okozta folyadékretenció", "slug": "vesebetegseg_okozta_folyadekretencio"}, {"name": "Anaemia", "slug": "anaemia"}, {"name": "Pitvarfibrilláció", "slug": "pitvarfibrillacio"}, {"name": "Nephrosis szindróma", "slug": "nephrosis_szindroma"}]'::jsonb,
  apn_approach='{"anamnesis": "Terhelési dyspnoe, orthopnoe, PND, oedema, testtömeg-változás, ismert szívbetegség, gyógyszerelés és adherencia.", "physical": "Pangásjelek (jugularis teltség, tüdőpangás, oedema), III. szívhang, tachycardia, hypoperfúzió jelei.", "data": "NT-proBNP/BNP, ionok, vese, vérkép, EKG, mellkasröntgen; echokardiográfia az EF meghatározásához.", "thinking": "Akut dekompenzáció vs. stabil krónikus állapot; kiváltó ok (ischaemia, arrhythmia, infekció, adherencia, só-/folyadékbevitel) keresése.", "consultation": "Új diagnózis, dekompenzáció, EF-alapú terápia beállítása orvosi döntést igényel.", "escalation": "Kardiogén shock, súlyos hypoxaemia, tüdőoedema azonnali ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "ESC 2021/2023 szívelégtelenség irányelv", "kezeles": "ESC 2021 HF (four pillars)"}'::jsonb, review_on='2027-08-01'
where slug='szivelegtelenseg';
update public.diseases set
  epidemiology='A leggyakoribb tartós ritmuszavar; prevalenciája az életkorral nő (>65 év jelentős). Fő szövődménye a cardioembóliás stroke.', pathophysiology='Rendezetlen pitvari elektromos aktivitás megszűnt hatékony pitvari kontrakcióval; pangás (különösen bal fülcse) → thrombus → embóliaforrás; szabálytalan kamrai válasz.',
  ddx='[{"name": "Pitvari flutter", "slug": "pitvari_flutter"}, {"name": "Supraventricularis tachycardia", "slug": "supraventricularis_tachycardia"}, {"name": "Gyakori supraventricularis extrasystolék", "slug": "gyakori_supraventricularis_extrasystolek"}, {"name": "Sinus tachycardia", "slug": "sinus_tachycardia"}, {"name": "Multifokális pitvari tachycardia", "slug": "multifokalis_pitvari_tachycardia"}]'::jsonb,
  apn_approach='{"anamnesis": "Palpitáció, dyspnoe, szédülés, syncope; kezdet és időtartam, kiváltó tényezők, stroke-rizikó (CHA2DS2-VASc), vérzésrizikó (HAS-BLED).", "physical": "Szabálytalan pulzus, pulzusdeficit, keringési instabilitás jelei, szívelégtelenség tünetei.", "data": "12 elvezetéses EKG (igazolás), ionok, pajzsmirigy, vese; echo a strukturális ok tisztázására.", "thinking": "Ritmus- vs. frekvenciakontroll mérlegelése; antikoaguláció indikációja a stroke-rizikó alapján, nem a ritmus típusa alapján.", "consultation": "Új AF, antikoaguláció indítása, instabil beteg orvosi döntést igényel.", "escalation": "Hemodinamikai instabilitás (hypotensio, mellkasi fájdalom, tüdőoedema) sürgős ellátást/kardioverziót igényelhet."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"ekg": "ESC 2024 AF irányelv", "kezeles": "ESC 2024 AF (AF-CARE)"}'::jsonb, review_on='2027-08-01'
where slug='pitvarfibrillacio';
update public.diseases set
  epidemiology='Gyakori, aluldiagnosztizált; fő rizikófaktor a dohányzás. Jelentős morbiditás, életminőség-romlás és mortalitás forrása.', pathophysiology='Krónikus légúti gyulladás → nem teljesen reverzibilis áramláskorlátozottság, légúti remodelling és/vagy emphysema; légúti csapdázódás, hyperinfláció, gázcserezavar.',
  ddx='[{"name": "Asthma bronchiale", "slug": "asthma_bronchiale"}, {"name": "Szívelégtelenség", "slug": "szivelegtelenseg"}, {"name": "Bronchiectasia", "slug": "bronchiectasia"}, {"name": "Tüdődaganat", "slug": "tudodaganat"}, {"name": "Interstitialis tüdőbetegség", "slug": "interstitialis_tudobetegseg"}, {"name": "Pulmonalis embolia", "slug": "pulmonalis_embolia"}]'::jsonb,
  apn_approach='{"anamnesis": "Dohányzási előzmény, terhelési dyspnoe, krónikus köhögés/köpet, exacerbatio-gyakoriság, tünetterhelés (CAT, mMRC).", "physical": "Meghosszabbodott kilégzés, sípolás, hordómellkas, segédizmok, cyanosis, perifériás oedema (cor pulmonale).", "data": "Spirometria (posztbronchodilatátor FEV1/FVC<0,7), pulzoximetria, szükség esetén vérgáz; mellkasröntgen a differenciáláshoz.", "thinking": "Stabil COPD vs. exacerbatio; asthmától és szívelégtelenségtől való elkülönítés; komorbiditások felmérése.", "consultation": "Diagnózis megerősítése, gyakori exacerbator, oxigénterápia mérlegelése orvosi döntést igényel.", "escalation": "Súlyos exacerbatio, akut légzési elégtelenség sürgős ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "GOLD 2024", "kezeles": "GOLD 2024"}'::jsonb, review_on='2027-08-01'
where slug='copd';
update public.diseases set
  epidemiology='Gyakori, jelentős morbiditású és mortalitású fertőzés, különösen idős és komorbid betegeknél. A CAP a leggyakoribb megjelenés.', pathophysiology='A tüdőparenchyma (alveolusok) fertőzéses gyulladása; gázcserezavar, konszolidáció; a kórokozó és a gazdaszervezet állapota határozza meg a súlyosságot.',
  ddx='[{"name": "Akut bronchitis", "slug": "akut_bronchitis"}, {"name": "COPD exacerbatio", "slug": "copd_exacerbatio"}, {"name": "Szívelégtelenség", "slug": "szivelegtelenseg"}, {"name": "Pulmonalis embolia", "slug": "pulmonalis_embolia"}, {"name": "Tüdődaganat", "slug": "tudodaganat"}, {"name": "Aspirációs pneumonia", "slug": "aspiracios_pneumonia"}, {"name": "Tuberculosis", "slug": "tuberculosis"}]'::jsonb,
  apn_approach='{"anamnesis": "Láz, köhögés, purulens köpet, mellkasi fájdalom, dyspnoe; kezdet, komorbiditások, aspiráció rizikója, közelmúltbeli kórházi tartózkodás.", "physical": "Tachypnoe, láz, lokalizált belégzési szörcszörej, tompulat, SpO2-csökkenés; súlyosság (NEWS2, CURB-65).", "data": "Mellkasröntgen, gyulladásos markerek, vérkép, vese/ionok, oximetria; súlyosságtól függően haemokultúra.", "thinking": "Súlyosság és ellátási hely megítélése (CURB-65/NEWS2); tipikus vs. atípusos kórokozók, komplikációk mérlegelése.", "consultation": "Súlyos pneumonia, szepszis-jel, romló oxigenizáció orvosi döntést és empirikus terápiát igényel.", "escalation": "Szepszis, légzési elégtelenség, magas CURB-65/NEWS2 sürgős ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "ATS/IDSA 2019 CAP", "kezeles": "ATS/IDSA 2019 CAP"}'::jsonb, review_on='2027-08-01'
where slug='pneumonia';
update public.diseases set
  epidemiology='Népbetegség, prevalenciája világszerte nő az elhízással párhuzamosan; gyakran évekig tünetmentes, szövődményesen kerül felismerésre.', pathophysiology='Inzulinrezisztencia és progresszív béta-sejt-diszfunkció → krónikus hyperglykaemia; mikro- és makrovaszkuláris szövődmények hosszú távon.',
  ddx='[{"name": "1-es típusú diabetes mellitus", "slug": "1_es_tipusu_diabetes_mellitus"}, {"name": "Szekunder diabetes", "slug": "szekunder_diabetes"}, {"name": "Stressz-hyperglykaemia", "slug": "stressz_hyperglykaemia"}, {"name": "Hyperosmolaris hyperglykaemiás állapot", "slug": "hyperosmolaris_hyperglykaemias_allapot"}, {"name": "Diabetikus ketoacidosis", "slug": "diabetikus_ketoacidosis"}]'::jsonb,
  apn_approach='{"anamnesis": "Polyuria, polydipsia, fogyás/fáradtság, rizikófaktorok (családi, obesitas), gyógyszerek, korábbi vércukorértékek.", "physical": "Testtömeg/haskörfogat, vérnyomás, lábstátusz (neuropathia, keringés, bőr), acanthosis nigricans.", "data": "Éhomi vércukor, HbA1c, vizelet, vese/eGFR, lipidek; szövődmény-szűrés (szem, láb, vese).", "thinking": "1-es vs. 2-es típus elkülönítése, akut hyperglykaemiás krízis kizárása; kardiovaszkuláris és renalis rizikó felmérése.", "consultation": "Új diagnózis, terápia beállítása/eszkalációja, szövődmény orvosi döntést igényel.", "escalation": "DKA/HHS gyanúja (súlyos hyperglykaemia, ketosis, tudatzavar) azonnali ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "ADA Standards of Care 2024", "kezeles": "ADA/EASD 2022 konszenzus"}'::jsonb, review_on='2027-08-01'
where slug='dm2';
update public.diseases set
  epidemiology='Gyakori, életveszélyes állapot magas mortalitással; a korai felismerés és ellátás kulcsfontosságú a kimenetel szempontjából.', pathophysiology='Fertőzésre adott diszregulált gazdaszervezeti válasz, amely életet veszélyeztető szervi diszfunkciót okoz; endothel-károsodás, mikrocirkulációs zavar, hypoperfúzió.',
  ddx='[{"name": "Nem szeptikus SIRS", "slug": "nem_szeptikus_sirs"}, {"name": "Hypovolaemiás shock", "slug": "hypovolaemias_shock"}, {"name": "Kardiogén shock", "slug": "kardiogen_shock"}, {"name": "Anaphylaxia", "slug": "anaphylaxia"}, {"name": "Tüdőembólia", "slug": "tudoembolia"}, {"name": "Akut hasi katasztrófa", "slug": "akut_hasi_katasztrofa"}, {"name": "Diabetikus ketoacidosis", "slug": "diabetikus_ketoacidosis"}]'::jsonb,
  apn_approach='{"anamnesis": "Fertőzésforrás keresése (légút, húgyút, has, bőr, katéter), immunstátusz, kezdet és gyors romlás.", "physical": "Vitálisok (láz/hypothermia, tachycardia, tachypnoe, hypotensio), tudatállapot, perfúziós jelek, gócok keresése.", "data": "Laktát, vérkép, CRP/PCT, vese/máj, ionok, haemokultúra és góc-specifikus mintavétel; qSOFA/SOFA, NEWS2.", "thinking": "Szepszis vs. szeptikus shock; a fertőzésforrás és a szervi diszfunkció gyors megítélése; időérzékeny beavatkozások.", "consultation": "Szepszis gyanúja azonnali orvosi értesítést, empirikus antibiotikumot és forráskontrollt igényel.", "escalation": "Szeptikus shock (perzisztáló hypotensio, emelkedett laktát) azonnali intenzív ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "Surviving Sepsis Campaign 2021", "kezeles": "Surviving Sepsis Campaign 2021 (1-órás bundle)"}'::jsonb, review_on='2027-08-01'
where slug='sepsis';
update public.diseases set
  is_stub=false, name='COPD exacerbatio', specialty='Pulmonológia', abbrev='AECOPD', aliases='{"COPD fellángolás","AECOPD"}',
  score_ids='{"cat","mmrc"}', ekg_ids='{}', body='{"brief_what": "A COPD tüneteinek akut, a napi ingadozáson túli rosszabbodása, amely a kezelés módosítását teszi szükségessé.", "brief_why": "Az APN korai felismeréssel, súlyosság-megítéléssel és a vörös zászlók azonosításával gyorsíthatja a megfelelő ellátást.", "when": ["Fokozódó dyspnoe", "Köpet mennyiségének/purulenciájának növekedése", "Fokozódó köhögés, sípolás", "Ismert COPD akut romlása"], "examine": ["Légzésszám, SpO2, segédizom-használat", "Tudatállapot (CO2-retenció jelei)", "Keringési státusz, láz", "Cyanosis, perifériás oedema"], "labs": "Pulzoximetria; súlyos esetben vérgáz (hypercapnia, acidosis). Gyulladásos markerek és mellkasröntgen az infekció/pneumonia és szövődmények megítélésére.", "ekg": "Komorbiditás vagy arrhythmia gyanúja esetén.", "imaging": "Mellkasröntgen pneumonia, pneumothorax, pangás kizárására.", "scores": "Súlyosság klinikai megítélése; NEWS2 a monitorozáshoz.", "red_flags": ["Súlyos nehézlégzés, kimerülés", "SpO2 tartós csökkenése oxigén mellett", "Tudatzavar, aluszékonyság (CO2-narkózis gyanúja)", "Cyanosis, hemodinamikai instabilitás", "Gyanús mellkasi fájdalom / új arrhythmia"], "apn_focus": ["Korai súlyosság-megítélés és monitorozás", "Kontrollált oxigénterápia mérlegelése (túl-oxigenizáció kerülése)", "Vörös zászlók azonnali jelzése", "Kiváltó ok (infekció, adherencia) feltárása"], "treatment": ["Kiváltó ok kezelése (gyakran légúti infekció)", "Hörgőtágító-terápia intenzitásának emelése (orvosi rendelés szerint)", "Szisztémás szteroid és/vagy antibiotikum mérlegelése irányelv szerint", "Kontrollált oxigén cél-SpO2 tartományban", "Súlyos esetben légzéstámogatás (NIV) mérlegelése"], "followup": ["Tünetek és SpO2 követése", "Kezelés-adherencia és inhalációs technika", "Exacerbatio-megelőzés, vakcináció, dohányzás-leszokás", "Fokozódás esetén újraértékelés"], "source_name": "GOLD 2024", "source_url": "https://goldcopd.org", "version": "1.0", "updated": "2026-08-24", "evidence": "Guideline-alapú (GOLD 2024)"}'::jsonb,
  epidemiology='A COPD-s betegek visszatérő eseménye; a gyakori exacerbatio rontja a prognózist és az életminőséget.', pathophysiology='Fokozott légúti gyulladás (gyakran vírusos/bakteriális infekció nyomán) → súlyosbodó áramláskorlátozottság, hyperinfláció, gázcserezavar, esetenként hypercapniás légzési elégtelenség.',
  ddx='[{"name": "Pneumonia", "slug": "pneumonia"}, {"name": "Szívelégtelenség", "slug": "szivelegtelenseg"}, {"name": "Pulmonalis embolia", "slug": "pulmonalis_embolia"}, {"name": "Pneumothorax", "slug": "pneumothorax"}, {"name": "Akut légzési elégtelenség", "slug": "akut_legzesi_elegtelenseg"}]'::jsonb,
  apn_approach='{"anamnesis": "Alaphelyzethez képesti változás, kiváltó tényezők (infekció, expozíció, adherencia), korábbi exacerbatiók és NIV-igény.", "physical": "Légzésszám, SpO2, segédizmok, tudatállapot, keringés, láz; a kimerülés jeleinek keresése.", "data": "Oximetria, szükség esetén vérgáz; mellkasröntgen és gyulladásos markerek a szövődmények és a differenciálás miatt.", "thinking": "Súlyosság és ellátási hely megítélése; pneumonia/PE/szívelégtelenség elkülönítése; CO2-retenció rizikójának felmérése.", "consultation": "Súlyos vagy nem javuló exacerbatio, hypercapnia, NIV-igény orvosi döntést igényel.", "escalation": "Akut légzési elégtelenség, tudatzavar, hemodinamikai instabilitás sürgős ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "GOLD 2024", "kezeles": "GOLD 2024"}'::jsonb, version='1.0', review_on='2027-08-01'
where slug='copd_exacerbatio';
update public.diseases set
  is_stub=false, name='Hypoglykaemia', specialty='Endokrinológia', abbrev='Hypo', aliases='{"Alacsony vércukor","Hypoglykaemiás állapot"}',
  score_ids='{}', ekg_ids='{}', body='{"brief_what": "Kórosan alacsony vércukorszint, amely autonóm és/vagy neuroglykopeniás tüneteket okoz; sürgős felismerést és korrekciót igényel.", "brief_why": "Az APN gyors felismeréssel és a megfelelő korrekció megkezdésével megelőzheti a súlyos, akár életveszélyes következményeket.", "when": ["Diabéteszes beteg gyanús tünetei", "Éhezés, kihagyott étkezés inzulin/szulfanilurea mellett", "Zavartság, viselkedésváltozás, izzadás, remegés", "Eszméletlenség, görcs ismeretlen okból"], "examine": ["Vércukor azonnali mérése", "Tudatállapot (GCS/AVPU)", "Autonóm tünetek (izzadás, tremor, tachycardia)", "Neuroglykopeniás jelek (zavartság, góctünet)"], "labs": "Kapilláris/vénás vércukor azonnal. Diabéteszes gyógyszerelés áttekintése; súlyos/ismétlődő eset esetén további kivizsgálás a nem diabéteszes ok irányába.", "ekg": "Kísérő panaszok vagy arrhythmia gyanúja esetén.", "imaging": "Rutinszerűen nem releváns.", "scores": "Tudatállapot követése (AVPU/GCS).", "red_flags": ["Eszméletvesztés, görcs", "Nem javuló tudatzavar korrekció után", "Ismétlődő hypoglykaemia", "Szulfanilurea vagy hosszú hatású inzulin miatti elhúzódó kockázat"], "apn_focus": ["Azonnali vércukormérés minden gyanús esetben", "Korrekció megkezdése az éberség szerint (per os vagy parenterális, protokoll szerint)", "Kiváltó ok feltárása és ismétlődés megelőzése", "Elhúzódó rizikó (szulfanilurea) felismerése és megfigyelés"], "treatment": ["Éber beteg: gyors felszívódású szénhidrát per os, majd komplex szénhidrát", "Nem éber/nem nyelő beteg: parenterális glükóz vagy glukagon protokoll szerint", "Vércukor újraellenőrzése és ismételt korrekció szükség szerint", "Ok kezelése; diabéteszes terápia felülvizsgálata"], "followup": ["Ismételt vércukor-ellenőrzés", "Gyógyszerelés és étkezési minta felülvizsgálata", "Beteg/gondozó edukáció a tünetekről és teendőkről", "Elhúzódó hatású szer esetén hosszabb megfigyelés"], "source_name": "ADA Standards of Care 2024", "source_url": "https://diabetesjournals.org", "version": "1.0", "updated": "2026-08-24", "evidence": "Guideline-alapú (ADA 2024)"}'::jsonb,
  epidemiology='Az inzulinnal vagy szulfanilureával kezelt diabéteszesek gyakori akut szövődménye; nem diabéteszes okok ritkábbak.', pathophysiology='A vércukor a fiziológiás küszöb alá csökken → ellenregulációs (autonóm) válasz, majd a központi idegrendszer glükózhiánya (neuroglykopenia); tartós/súlyos hypoglykaemia neurológiai károsodást okozhat.',
  ddx='[{"name": "Stroke", "slug": "stroke"}, {"name": "Epilepsziás roham", "slug": "epilepszias_roham"}, {"name": "Alkoholos/toxikus állapot", "slug": "alkoholos_toxikus_allapot"}, {"name": "Sepsis", "slug": "sepsis"}, {"name": "Szinkópé", "slug": "szinkope"}, {"name": "Pszichiátriai állapot", "slug": "pszichiatriai_allapot"}]'::jsonb,
  apn_approach='{"anamnesis": "Diabéteszes gyógyszerelés, étkezés/alkohol, fizikai terhelés, korábbi hypoglykaemiák, tünetek kezdete.", "physical": "Tudatállapot, autonóm és neuroglykopeniás jelek, vitálisok; góctünetek keresése.", "data": "Azonnali vércukor; szükség szerint gyógyszerszint/kiegészítő vizsgálat a nem diabéteszes ok irányába.", "thinking": "Hypoglykaemia mint reverzibilis ok kizárása MINDEN akut tudatzavarnál; kiváltó ok és ismétlődés rizikójának megítélése.", "consultation": "Súlyos, ismétlődő vagy tisztázatlan eredetű hypoglykaemia orvosi döntést igényel.", "escalation": "Eszméletvesztés, görcs, korrekcióra nem reagáló állapot sürgős ellátást igényel."}'::jsonb, evidence_levels='{"guideline","expert"}', validation_status='review_pending',
  block_sources='{"labor": "ADA 2024", "kezeles": "Helyi hypoglykaemia-protokoll + ADA 2024"}'::jsonb, version='1.0', review_on='2027-08-01'
where slug='hypoglykaemia';
update public.diseases set
  is_stub=false, name='Akut vesekárosodás', specialty='Nefrológia-urológia', abbrev='AKI', aliases='{"AKI","Akut veseelégtelenség"}',
  score_ids='{}', ekg_ids='{"hyperk"}', body='{"brief_what": "A vesefunkció órák–napok alatti hirtelen romlása (kreatinin-emelkedés és/vagy vizeletürítés csökkenése); gyakran reverzibilis, ha az okot időben kezelik.", "brief_why": "Az APN a rizikóbetegek felismerésével, a folyadék- és gyógyszerelési szempontok követésével és a vörös zászlók jelzésével csökkentheti a szövődményeket.", "when": ["Csökkenő vizeletmennyiség", "Emelkedő kreatinin/karbamid", "Volumenhiány (hányás, hasmenés, vérzés, sepsis)", "Nefrotoxikus gyógyszer vagy kontrasztanyag expozíció"], "examine": ["Volumenstátusz (turgor, nyálkahártyák, vérnyomás, JVP)", "Diurézis/folyadékmérleg", "Húgyúti obstrukció jelei (telt hólyag)", "Sepsis vagy szívelégtelenség jelei"], "labs": "Kreatinin, karbamid, ionok (különösen kálium), sav-bázis, vérkép; vizeletvizsgálat. A KDIGO stádiumbeosztás a kreatinin-emelkedés és a diurézis alapján.", "ekg": "Hyperkalaemia gyanúja esetén sürgősen (magas T-hullám, széles QRS).", "imaging": "Vese-ultrahang posztrenalis ok (obstrukció) kizárására.", "scores": "KDIGO AKI-stádium (1–3).", "red_flags": ["Hyperkalaemia (EKG-eltéréssel)", "Anuria / gyorsan romló funkció", "Folyadéktúlterhelés, tüdőoedema", "Súlyos metabolikus acidosis", "Uraemiás tünetek (tudatzavar, pericarditis)"], "apn_focus": ["Rizikóbetegek azonosítása és a vesefunkció követése", "Folyadékstátusz és -mérleg gondos megítélése", "Nefrotoxikus gyógyszerek és kontraszt kerülése/felülvizsgálata", "Hyperkalaemia és a dialízis-indikációk vörös zászlóinak felismerése"], "treatment": ["Ok kezelése (volumenpótlás vagy -megvonás a státusz szerint; sepsis/ obstrukció ellátása)", "Nefrotoxinok elhagyása, gyógyszeradagok veseműködéshez igazítása (orvosi rendelés szerint)", "Elektroliteltérések, különösen hyperkalaemia kezelése protokoll szerint", "Súlyos/refrakter esetben vesepótló kezelés mérlegelése"], "followup": ["Kreatinin, ionok és diurézis ismételt követése", "Gyógyszerelés újraértékelése", "A kiváltó ok rendezésének ellenőrzése", "Krónikus vesebetegséggé progresszió szűrése"], "source_name": "KDIGO AKI 2012 (és aktuális frissítések)", "source_url": "https://kdigo.org", "version": "1.0", "updated": "2026-08-24", "evidence": "Guideline-alapú (KDIGO)"}'::jsonb,
  epidemiology='Kórházi betegek gyakori szövődménye; rontja a mortalitást és növeli a krónikus vesebetegség kockázatát. Rizikó: idős kor, CKD, sepsis, nagy műtét, nefrotoxinok.', pathophysiology='Prerenalis (hypoperfúzió), renalis (parenchyma-károsodás, pl. akut tubuláris nekrózis) vagy posztrenalis (obstrukció) mechanizmus → csökkent GFR, salakanyag-retenció, folyadék- és elektrolitzavar.',
  ddx='[{"name": "Krónikus vesebetegség", "slug": "kronikus_vesebetegseg"}, {"name": "Hypovolaemia / dehidráció", "slug": "hypovolaemia_dehidracio"}, {"name": "Sepsis", "slug": "sepsis"}, {"name": "Szívelégtelenség", "slug": "szivelegtelenseg"}, {"name": "Húgyúti obstrukció", "slug": "hugyuti_obstrukcio"}, {"name": "Hyperkalaemia", "slug": "hyperkalaemia"}]'::jsonb,
  apn_approach='{"anamnesis": "Folyadékvesztés/-bevitel, vizeletürítés változása, gyógyszerek (NSAID, RAAS-gátló, diuretikum), kontraszt, ismert vesebetegség.", "physical": "Volumenstátusz, vérnyomás, diurézis, telt hólyag, sepsis vagy szívelégtelenség jelei.", "data": "Kreatinin-trend, ionok (kálium!), sav-bázis, vizelet; vese-UH obstrukció kizárására; KDIGO-stádium.", "thinking": "Pre-/renalis/posztrenalis ok elkülönítése; reverzibilis tényezők és a sürgős dialízis-indikációk gyors felmérése.", "consultation": "Stádium-emelkedés, hyperkalaemia, oliguria/anuria, tisztázatlan ok orvosi/nefrológiai konzultációt igényel.", "escalation": "Életveszélyes hyperkalaemia, refrakter folyadéktúlterhelés, súlyos acidosis, uraemiás szövődmény sürgős ellátást igényel."}'::jsonb, evidence_levels='{"guideline","evidence"}', validation_status='review_pending',
  block_sources='{"labor": "KDIGO AKI", "ekg": "Hyperkalaemia EKG-jelei", "kezeles": "KDIGO AKI + helyi protokoll"}'::jsonb, version='1.0', review_on='2027-08-01'
where slug='akut_vesekarosodas';
